- id: poetry-export
  name: Poetry Export
  description: Prevent desync between poetry and requirements.txt
  entry: pre_commit_hooks.export:main
  language: python
  types: [text]
  files: ^requirements\.txt$
  additional_dependencies: [poetry]
