- id: poetry-export
  name: Poetry Export
  description: Prevent desync between poetry and requirements.txt
  entry: pre_commit_hooks/export.sh
  language: script
  types: [text]
  files: ^requirements.txt$
